version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle-version-catalog"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

