[versions]
assertj = "3.24.2"
junit = "5.8.1"
kotlin = "1.8.21"

[libraries]
flyway = "org.flywaydb:flyway-core:9.17.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin" }
