# Worfklow for https://jmfayard.github.io/refreshVersions/

name: RefreshVersions

on:
  workflow_dispatch:
  schedule:
   - cron: '0 7 * * 1'

jobs:
  "Refresh-Versions":
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: step-0
        name: check-out
        uses: actions/checkout@v3
        with:
          ref: main
      - id: step-1
        name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - id: step-3
        name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions
          build-root-directory: refreshVersions-plugin
      - id: step-4
        name: Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: 'version-upgrades/new-versions-available'
          delete-branch: true
          commit-message: 'Dependency upgrade available'
          title: Upgrade dependencies
          body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates'
